### ISSUE TITLE
CLient with special IP ?

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/pihole_ynh#14]
Hello there, 

so i started using pihole, and i see this : 

![image](https://user-images.githubusercontent.com/32466950/35486813-bbbc701a-0473-11e8-9548-b3fe7a3edad9.png)

and when i clike on it i have ; 

![image](https://user-images.githubusercontent.com/32466950/35486817-ca10f9e2-0473-11e8-98b0-45208f9483f4.png)

what that's means ?

how i can have  computer with ip like this on my network ?

i have a zombie virus on my lan ?

can hep lto understand this please ?

**Comment by maniackcrudelis** [comment]
This ip, 185.2.81.90, is linked to the domain server.myfreenetwork.com, which doesn't seem to exist in any dns. It's probably a local domain, defined somewhere in your network.

But, this domain and this IP are linked to the domain worldstream.nl that seems to provide VPS.

I think either there's a router or other thing like that that try to contact a server, or a software.
I don't know much about the domain activum.nu, but with a name like that. Probably you have somewhere a device or a software which try to contact a website to get an activation.

**Comment by gamersalpha** [comment]
ok some other client : 


![image](https://user-images.githubusercontent.com/32466950/35578739-44af1ce8-05e5-11e8-8ef8-d44341a1b73a.png)
![image](https://user-images.githubusercontent.com/32466950/35578751-4b166758-05e5-11e8-98df-84b8c3e3fbc7.png)


and 

![image](https://user-images.githubusercontent.com/32466950/35578768-55be4d1a-05e5-11e8-89c7-ae8c4b811379.png)
![image](https://user-images.githubusercontent.com/32466950/35578778-5ccb888e-05e5-11e8-96c0-df40e836206d.png)


i really don't understand how i can get this client on my network, that's a mystery for me



in the exelrnt page of pi-hole i have only the 24H historique, can i have more, weeks month years ??

**Comment by maniackcrudelis** [comment]
[shadowserver](https://www.shadowserver.org/wiki/), I don't know what on your network uses that.

PiHole restrict itself the log to 24 hours. Have a look to its cronjob to change that. `/etc/cron.d/pihole`

And about the usage of your dns by other servers on internet. Yes it's possible, but it's probably not the case here.
To prevent this usage, check if your port 53 is close on your router. This port should be open only on your raspi, and only on your local network.

**Comment by Spartacus2018** [comment]
ok u can close, 

the problem is my server is on internet !!

so noww i block with my  routeur the dns service from internet

it's ok now
