### ISSUE TITLE
bug yunohost install

### ISSUE THREAD

**Issue by dudjima** [YunoHost-Apps/pihole_ynh#15]
I can't install package on yunohost(ssowat generate inifinite). i try with an other yunohost and it's the same problem. 
sorry i can't explain more :/ 

yunohost-cli.log : 
https://framabin.org/?1b7dfda2b2d499dd#5jE9AskW+15eOpkvZiMvNnD52esEr/cmOI1A8hWPgDc=

**Comment by maniackcrudelis** [comment]
Can you give me a bigger part of the log.
A complete log would be perfect ;)

**Comment by dudjima** [comment]
just log yunohost_cli ?

**Comment by maniackcrudelis** [comment]
Just the part of yunohost-cli.log about the installation of Pi-Hole.

**Comment by dudjima** [comment]
ok 
https://framabin.org/?c1d6c98d6aefccd2#5tz/vvMxMQHkd3YjN22yN7HCTZHA8oa03Vic3VFWuMQ=

thank you

**Comment by maniackcrudelis** [comment]
So can you retry to install Pi-Hole, and copy the whole log given during the installation.
Because, here, there's only a small part of the remove part of Pi-Hole after it have failed to be set up.

**Comment by dudjima** [comment]
Hop le fichier qui va bien sorry 

https://framabin.org/?331aed3f800619bb#jBqGO34Q6+feVnRFXB2aLT6XNdoJnsPEsy7QNEamrc8=

**Comment by maniackcrudelis** [comment]
As usual, `_common.sh: line 573: mail: command not found`
Just install mailutils
```
sudo apt-get install mailutils
```
This problem will be soon fixed in YunoHost.

**Comment by dudjima** [comment]
thank you, you're so fast :+1: 

it's fix
