### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by bourreP** [YunoHost-Apps/pihole_ynh#37]
Hi!

I found a problem in your installation script:

`ip route | grep default` give me:
```
default via 192.168.0.254 dev eth0 proto static metric 100
default via 192.168.0.254 dev wlan0 proto static metric 600
```

So,
https://github.com/YunoHost-Apps/pihole_ynh/blob/1d2e63fd0c5107a1646555933a2be0a327b58517/scripts/install#L196

Give me: 
```
eth0
wlan0
```

And this command fail:

https://github.com/YunoHost-Apps/pihole_ynh/blob/1d2e63fd0c5107a1646555933a2be0a327b58517/scripts/install#L225

Maybe you should take the first interface?

I've succeeded to install this application by removing my route:

```
route del -net 0.0.0.0 gw 192.168.0.254 netmask 0.0.0.0 dev wlan0
```

**Comment by maniackcrudelis** [comment]
Indeed, thanks for having find this.
Fixed in an ongoing commit.
