### ISSUE TITLE
Change the lan address ?

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/pihole_ynh#4]
Hi
What if I wanted to change the lan address of the server, For eg. from 192.168.1.50 to 192.168.1.100 ? Will  I have to do some changes for the app to work ?

**Comment by maniackcrudelis** [comment]
I never really try to do that.
But, I think the only thing to do is to change the ip adress in the /etc/hosts of your server.

**Comment by anmol26s** [comment]
I will try it soon and report here, until then this can be closed.
