### ISSUE TITLE
Update to 4.2

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/pihole_ynh#40]
Just a new issue to notify that 4.2 is available :slightly_smiling_face:

**Comment by maniackcrudelis** [comment]
As explained in the readme, this package won't update PiHole to version 4 or later, because since version 4, PiHole is using is own version of dnsmasq. But, as YunoHost is using dnsmasq, we can't install another version.
So, unless PiHole allow to use an existing version of dnsmasq, this package won't update PiHole anymore.

**Comment by supermamie** [comment]
The version included in yunohost is a fork of dnsmasq or is it the vanilla version ?
If it is not a fork, it should be possible tu use pi-hole's dnsmask as it should be the same one plus some features.

I have no idea on how to try this :disappointed:

**Comment by maniackcrudelis** [comment]
Unless we're sure there's no conflict, we can't risk to break dnsmasq in YunoHost.

**Comment by supermamie** [comment]
I just found this : https://discourse.pi-hole.net/t/ftl-offline-on-yunohost/14547
Maybe @liberodark can give some feedback about his tests with pi-hole 4 ?

**Comment by lightnin** [comment]
Seems like there might be security issues with remaining forever on an old, outdated version. Shouldn't this be removed from the Yunohost app catalog, or at least downgrade its score?

**Comment by maniackcrudelis** [comment]
This app is behind the sso and won't be publicly accessible, how could it have a security issue ?
The app works only on a local network and provide a list of domain to block to dnsmasq. Only dnsmasq could be a risk, and that part is up to debian team.

**Comment by lightnin** [comment]
> This app is behind the sso and won't be publicly accessible, how could it have a security issue ?
> The app works only on a local network and provide a list of domain to block to dnsmasq. Only dnsmasq could be a risk, and that part is up to debian team.

Hmm, here's a "you better upgrade soon" notice the pi-hole team circulated not too long ago. Perhaps it doesn't really apply to this version since it is from before dnsmasq was included with Pi-hole.
https://pi-hole.net/2021/01/19/pi-hole-ftl-v5-5-released-update-today/#page-content

**Comment by maniackcrudelis** [comment]
This notice is about a security issue on dnsmasq, which concern Pi-Hole from version 4 or later only.

**Comment by tituspijean** [comment]
The app is now on 5.4. 🚀
