### ISSUE TITLE
App is not accessible

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/pihole_ynh#45]
Hello,

I just installed the app, but it is unusable. It doesn't appear in my portal and typing its URL manually acts as if i didn't installed it (it redirects me to the portal).

**Comment by maniackcrudelis** [comment]
Are you sure the app is correctly installed ?
Do you have a log of your installation ?

**Comment by stemy2** [comment]
Yes, the log says «installed successfully».
