### ISSUE TITLE
Cannot use the app after enabling hotspot app

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/pihole_ynh#5]
Internet connection becomes unavailable after I enable the hotspot app https://github.com/labriqueinternet/hotspot_ynh and I have to change the DNS of the all the hosts.
I use hotspot app for piratebox app to share files locally. On restarting the server the hotspot app is disabled and pihole works but as soon I enable the hotpost app the pihole DNS stops working.

**Comment by maniackcrudelis** [comment]
Hi anmol26s

There's a conflict with hotspot_ynh, pihole_ynh use simply dnsmasq, as it configured in YunoHost. And allow you to use it, and by the way the dns providers configured in your YunoHost.
But, hotspot_ynh define its own dns providers (https://github.com/labriqueinternet/hotspot_ynh/blob/master/scripts/install#L126-L129).
So, theses 2 apps can't be used at the same time.

**Comment by anmol26s** [comment]
Hi maniackcridelis
Can I use use separate dns for both pihole and hotspot? Or configure the dns to behave differently  for particular ip range? Or maybe use different dns for different interfaces because hotspot uses wifi dongle and pihole uses lan to connect to modem?

But it may or may not be possible, strangely when ever I restart the server and re-enable the hotspot (status is always down after the server restart) both pihole and hotspot work. Its only if I restart pihole or dnsmasq the pihole stops working.

**Comment by maniackcrudelis** [comment]
I don't know how hotspot works, but I guess there something about dnsmasq config.
What I can say that pihole doesn't change the config of dnsmasq, BUT, adds an additionnal config file in dnsmasq.d.
And, by experience, I can say there's an error case if you duplicate some dnsmasq keyword in the config. So, a thing you can do that trying to reboot dnsmasq and check its log to see if there's an error about that.
