### ISSUE TITLE
No blocking via ipv6

### ISSUE THREAD

**Issue by ashwinvis** [YunoHost-Apps/pihole_ynh#50]
I have added pihole as a DNS server, and configured both custom ipv4 and ipv6 DNS servers to forward to. But this happens:

![Screenshot_2020-03-17 Pi-hole Admin Console](https://user-images.githubusercontent.com/9155111/76845249-e35ceb00-683e-11ea-8475-a00cf403f059.png)

I wonder if this has to do with a blank ipv6 localhost config:

**Comment by ashwinvis** [comment]
See:

https://github.com/YunoHost-Apps/pihole_ynh/blob/6ecbf20ad7df3a2af89a2ccad1c04c3837a64bc3/scripts/actions/reset_default_config#L49

**Comment by maniackcrudelis** [comment]
Hello

I'm not using ipv6 so I can't tell you what to do to fix this issue.
But if you find out the way to make it work, I'll gladly add the fix to the package for anyone else using ipv6

**Comment by ashwinvis** [comment]
I made the change to `IPV6_ADDRESS=::1` but it did not change anything... until I read this FAQ on using [unique local addresses (ULA) for ipv6](https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127). I also had to rely on an [ipv6 prefix generator](https://simpledns.plus/private-ipv6) to make appopriate changes on my router.

**Comment by maniackcrudelis** [comment]
Huh sorry to much to read for my current laziness... :D
In short terms, what was the solution ?

**Comment by ashwinvis** [comment]
Enable ULA in the router.
