### ISSUE TITLE
Warning in install

### ISSUE THREAD

**Issue by stevenmache** [YunoHost-Apps/pihole_ynh#56]
For info, an error message on the install on ynh 4.2
Packagers /!\ This app manually modified some system configuration files! This should not happen! If you need to do so, you should implement a proper conf_regen hook. Those configuration were affected: - /etc/dnsmasq.conf

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost-Apps/pihole_ynh/pull/63
