### ISSUE TITLE
 Request from unknown clients. Is it a security risk?

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/pihole_ynh#6]
I was checking the logs in pi-hole web interface. And I was request from unknown clients which is not on my local network. Is it possible to connect to the pi-hole DNS from outside the lan?
![selection_070](https://user-images.githubusercontent.com/5068843/32560785-84d9d9da-c4d0-11e7-84d3-01287bd7a1b1.png)

**Comment by anmol26s** [comment]
Can my public ip be used as DNS for pi-hole? I am seeing new public ip's using the DNS in pi-hole web interface. @maniackcrudelis

**Comment by anmol26s** [comment]
The DNS Pi-hole can be used by public IP too. Is there a way to block the public ip and only use Pi-hole for internal network?

**Comment by maniackcrudelis** [comment]
Hi anmol

sorry like often, github doesn't send me any email for this issue...

So, it's probably not linked to pi-hole, but only to dnsmasq, and that means also pi-hole give you only a way to see what's happen...
Can you check if your port 53 is open in your router ? In this case, close this port would prevent any external request to your dnsmasq.

**Comment by anmol26s** [comment]
Yes my port 53 is open and I think the Yunohost open it by default while installation.

**Comment by maniackcrudelis** [comment]
Yes it was, but we fixed that yesterday
https://github.com/YunoHost/yunohost/pull/362

You can close it in your router.

**Comment by anmol26s** [comment]
@maniackcrudelis 
Thanks
