### ISSUE TITLE
VPS: Unable to speak to outside world

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/pihole_ynh#8]
After installing to the VPS the VPS stopped pinging to outside world. I can connect to the server from outside but no outbound request can take place. 
I uninstalled the Pihole still I can't connect to the outside world from the server.

**Comment by maniackcrudelis** [comment]
Do you any clue about what's going on ?

**Comment by anmol26s** [comment]
It was a test VPS for the openvpn and Pihole. I wanted a dns for friends hosted publicly. So this VPS has nothing important. I have even given the root to the VPS providers to test. They reported to stop all yunohost-firewall,fail2ban and it will work. But did not worked for me. 

If you want to see in the VPS you are most welcomed otherwise I will reinstall it to test [Archivist](https://github.com/YunoHost-Apps/archivist_ynh).

**Comment by anmol26s** [comment]
Can you test it on fresh install VPS as I face this issue on all VPS.I don't understand why it works at home but not on the VPS. After installing Pi-Hole you need to restart the VPS then the outside world becomes unreachable. I want to serve pi-hole as open DNS .
