### ISSUE TITLE
Small permission issue on various files

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/pihole_ynh#81]
### Describe the bug
This doesn't cause security concerns, as the group owner is "root". However, there are some warnings in the logs about permissions on multiple files. They should have `rw-r--r--` instead of `rw-rw-r--` (`chmod g-w`, or 644 instead of 664).
* I received a cron mail informing me that `/etc/pihole/logrotate` had the wrong permissions:
  > error: Ignoring /etc/pihole/logrotate because it is writable by group or others.
* In the system journal, there was the same complaint about `/etc/cron.d/pihole`. I fixed it, then I received the mail above the day after.

### Context
I'll fill in the rest of the template later, if I have time. I'm not sure that's necessary.

### Expected behavior

Out-of-the-box permissions should be adequate.

**Comment by ericgaspar** [comment]
Strange, I get `-rw-r--r--` for `/etc/pihole/logrotate` and for `/etc/cron.d/pihole` out of the box... (from the testing branch)

**Comment by MayeulC** [comment]
Weird. I guess I can close, feel free to reopen later if someone else reports it.
